apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  name: kubernetes-nmstate-operator
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace

