apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: corporate-ad
    mappingMethod: claim
    ldap:
      bindDN: "CN=svc_edge1_ldap,OU=service_admin,DC=kodevirtual,DC=com"

