apiVersion: v1
kind: Secret
metadata:
  name: ldap-group-sync
  namespace: group-sync-operator
type: Opaque
data:
  username: Y249c3ZjX2h1Yl9sZGFwLG91PXNlcnZpY2VfYWRtaW4sZGM9a29kZXZpcnR1YWwsZGM9Y29t
  password: Vk13YXJlMSE=
