apiVersion: v1
kind: Secret
metadata:
  name: ldap-group-sync
  namespace: group-sync-operator
type: Opaque
data:
  username: Y249c3ZjX2VkZ2UxX2xkYXAsb3U9c2VydmljZV9hZG1pbixkYz1rb2RldmlydHVhbCxkYz1jb20=
  password: Vk13YXJlMSE=
